# Generated by Django 5.0.6 on 2024-05-21 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_storesize'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoreSize',
            new_name='store_Size',
        ),
    ]
