# Generated by Django 5.0.6 on 2024-05-21 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_rename_storesize_store_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='foot_sizes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
