# Generated by Django 5.0.6 on 2024-05-21 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_product_foot_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.DeleteModel(
            name='store_Size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='foot_sizes',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
