# Generated by Django 5.0.6 on 2024-05-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_product_foot_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='foot_sizes',
            field=models.CharField(choices=[('EU36', 'EU 36'), ('EU37', 'EU 37'), ('EU38', 'EU 38'), ('EU39', 'EU 40'), ('EU41', 'EU 41'), ('EU42', 'EU 42'), ('EU43', 'EU 43'), ('EU44', 'EU 44'), ('EU45', 'EU 45')], max_length=10),
        ),
    ]
