# Generated by Django 5.0.6 on 2024-05-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_order_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
