# Generated by Django 5.0.6 on 2024-05-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_order_shipping_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Shipping_address',
        ),
        migrations.AddField(
            model_name='order',
            name='cod_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='gcash_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('GCASH', 'GCash'), ('COD', 'Cash on Delivery')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(default='GCASH'),
            preserve_default=False,
        ),
    ]
