# Generated by Django 5.0.6 on 2024-06-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0018_alter_shippingaddress_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='sender_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
