# Generated by Django 5.0.6 on 2024-06-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0020_order_date_delivered_order_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_option',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
