# Generated by Django 5.0.6 on 2024-06-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0021_order_payment_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gcash_transaction_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
