# Generated by Django 5.0.6 on 2024-06-07 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0022_order_gcash_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='gcash_transaction_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_option',
        ),
    ]
